
name: ai_trading_signals
description: A Flutter project.

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  supabase_flutter: ^2.5.0
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

